#### IMPORTING NECESSARY LIBRARIES

In [14]:
import numpy as np
import pandas as pd

In [15]:
# Extracting data
yankee_df = pd.read_csv(r'C:\Users\user\Desktop\Yankee Ecommerce\Yankee_Ecommerce_Study_Case\dataset\raw data\yanki_ecommerce.csv')

In [16]:
yankee_df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price', 'Quantity', 'Total_Price',
       'Order_Date', 'Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code', 'Email', 'Phone_Number', 'Payment_Method',
       'Transaction_Status'],
      dtype='object')

### DATA CLEANING

In [17]:


#drop missing values
yankee_df.dropna(subset =['Order_ID' , 'Customer_ID'], inplace=True)

In [18]:
yankee_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 2 to 1019
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            1000 non-null   object
 1   Customer_ID         1000 non-null   object
 2   Customer_Name       1000 non-null   object
 3   Product_ID          1000 non-null   object
 4   Product_Name        1000 non-null   object
 5   Brand               1000 non-null   object
 6   Category            1000 non-null   object
 7   Price               1000 non-null   float64
 8   Quantity            1000 non-null   int64
 9   Total_Price         1000 non-null   float64
 10  Order_Date          1000 non-null   object
 11  Shipping_Address    1000 non-null   object
 12  City                1000 non-null   object
 13  State               999 non-null    object
 14  Country             1000 non-null   object
 15  Postal_Code         1000 non-null   int64
 16  Email               1000 non-null   object
 17  Phone_Number        1000 non-null   object
 18  Payment_Method      1000 non-null   object
 19  Transaction_Status  1000 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 164.1+ KB

In [20]:
# convert Order_Date from string to datetime
yankee_df['Order_Date'] = pd.to_datetime(
    yankee_df['Order_Date'],
    dayfirst=True
)

In [21]:
# customer table
customer_df  = yankee_df[[ 'Customer_ID', 'Customer_Name' , 'Email', 'Phone_Number']].copy().drop_duplicates().reset_index(drop= True)
customer_df.head()

,Customer_ID,Customer_Name,Email,Phone_Number
0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,Dominic Buchanan,margaret97@example.com,259.603.6134
1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,Daniel Allen,angela55@example.com,+1-869-659-4272x982
2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,Daniel Schmidt,wayne59@example.org,292.840.0975x724
3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,John Gonzalez,qsherman@example.com,+1-643-561-3912x262
4,81b513ad-5c02-48cf-bff0-39e1440c4d22,Amber Benitez,derek85@example.com,3424148376

In [22]:
#products table

products_df = yankee_df[['Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price',]].copy().drop_duplicates().reset_index(drop= True)
products_df.head()

,Product_ID,Product_Name,Brand,Category,Price
0,2ef6e8fa-6a36-4515-b1c2-a0a700abf386,despite,"Lawson, Stone and Campos",perfume oil,250.57
1,3ba38e01-f8e7-4af2-9246-87ef0961d4f5,sea,Washington Group,perfume oil,179.81
2,a58c53bd-a34b-4541-b926-bec9eb84cac2,suddenly,Rodgers Ltd,perfume oil,600.55
3,e6021be5-90be-4199-b6c6-82542fb2973c,site,"Wilson, Scott and Johnson",perfume oil,414.36
4,60127671-ab32-4fb5-bfeb-1a7782ad835e,act,"Riddle, Alvarez and Robinson",perfume,704.05

In [28]:
# shipping table
shipping_address_df = yankee_df[['Customer_ID','Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code']].copy().drop_duplicates().reset_index(drop= True) 

shipping_address_df.index.name = 'shipping_ID'
shipping_address_df =shipping_address_df.reset_index()

In [23]:
# orders table
orders_df = yankee_df[['Order_ID', 'Customer_ID','Product_ID','Quantity', 'Total_Price' , 'Order_Date']].copy().drop_duplicates().reset_index(drop= True)

In [26]:
#payment methods table

payment_method_df = yankee_df[['Order_ID', 'Payment_Method',
       'Transaction_Status']]

In [29]:
customer_df.to_csv(r'dataset\clean data\customers' , index = False)
products_df.to_csv(r'dataset\clean data\products' , index = False)
orders_df.to_csv(r'dataset\clean data\orders' , index = False)
shipping_address_df.to_csv(r'dataset\clean data\shipping_address' , index = False)
payment_method_df.to_csv(r'dataset\clean data\payment_method' , index = False)

In [5]:
yankee_df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price', 'Quantity', 'Total_Price',
       'Order_Date', 'Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code', 'Email', 'Phone_Number', 'Payment_Method',
       'Transaction_Status'],
      dtype='object')